steps:
  - id: "branch name"
    name: "alpine"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        echo "***********************"
        echo "$BRANCH_NAME"
        echo "***********************"
  - id: "deploy manifest"
    name: "google/cloud-sdk:272.0.0"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        gcloud container clusters get-credentials \
          qicoo-k8s-cluster-001 \
          --region asia-northeast1

        kubectl get node

        gcloud kms decrypt \
          --location asia-northeast1 \
          --keyring qicoo-kms-02 \
          --key qicoo-kms-02-key \
          --plaintext-file manifests/10_qicoo-api/11_config/qicoo-secret.yaml \
          --ciphertext-file secrets/qicoo-secret.yaml.enc

        gcloud kms decrypt \
          --location asia-northeast1 \
          --keyring qicoo-kms-02 \
          --key qicoo-kms-02-key \
          --plaintext-file manifests/20_mysql_operator/21_operator/mysql-secret.yaml \
          --ciphertext-file secrets/mysql-secret.yaml.enc

        # kubectl apply --dry-run -f manifests -R && kubectl apply -f manifests -R
        kubectl apply -f manifests -R
