apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate
metadata:
  name: qicoo-tls-cert
  namespace: qicoo
spec:
  domains:
    - qicoo.tokyo
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: qicoo-ingress
  namespace: qicoo
  annotations:
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.global-static-ip-name: "qicoo-tokyo"
    networking.gke.io/managed-certificates: qicoo-tls-cert
spec:
  backend:
    serviceName: qicoo-front
    servicePort: 37000
  rules:
  - http:
      paths:
      - path: /api/v1/*
        backend:
          serviceName: qicoo-api
          servicePort: 37000