apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: qicoo-tls-cert
  namespace: qicoo
spec:
  domains:
    - qicoo.tokyo
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qicoo-ingress
  namespace: qicoo
  annotations:
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.global-static-ip-name: "qicoo-tokyo"
    networking.gke.io/managed-certificates: qicoo-tls-cert
spec:
  defaultBackend:
    service:
      name: qicoo-front
      port:
        number: 37000
  rules:
  - http:
      paths:
      - path: /api/v1/*
        pathType: ImplementationSpecific
        backend:
          service:
            name: qicoo-api
            port:
              number: 37000