apiVersion: mysql.oracle.com/v2alpha1
kind: InnoDBCluster
metadata:
  name: mysql-qicoo2db
  namespace: qicoo
spec:
  secretName: mysql-root-password-secret
  instances: 3
  version: 8.0.25
  router:
    instances: 1
    version: 8.0.25
