apiVersion: apps/v1
kind: Deployment
metadata:
  name: qicoo-api
  namespace: qicoo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: qicoo-api
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: qicoo-api
    spec:
      initContainers: 
        - name: init-db
          image: mysql/mysql-router:8.0.25
          command:
            - "/bin/bash"
            - "-cx"
            - "echo CREATE DATABASE IF NOT EXISTS qicoo2db | mysql -h${MYSQL_HOST} -P${MYSQL_PORT} -u${MYSQL_USER} -p${MYSQL_PASSWORD}"
          env:
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_HOST
                  name: qicoo-api-config
            - name: MYSQL_PORT
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_PORT
                  name: qicoo-api-config
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  key: MYSQL_USER
                  name: qicoo-secret
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MYSQL_PASSWORD
                  name: qicoo-secret
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 102Mi
      containers:
        - name: qicoo-api
          image: cndjp/qicoo-api-kt:8d77fe524b5983a04eb13ec51b6a17c2684be030
          envFrom:
            - configMapRef:
                name: qicoo-api-config
            - secretRef:
                name: qicoo-secret
          livenessProbe:
            failureThreshold: 2
            httpGet:
              path: /hc
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          readinessProbe:
            failureThreshold: 2
            httpGet:
              path: /api/v1/questions
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 30
          ports:
            - containerPort: 8081
              name: http
          resources:
            limits:
              cpu: 1000m
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 102Mi
          securityContext:
            privileged: false
            readOnlyRootFilesystem: true
            runAsUser: 12345
